version: "2"

run:
  timeout: 3m

linters:
  enable:
    - bodyclose
    - copyloopvar
    - durationcheck
    - errname
    - errorlint
    - fatcontext
    - goconst
    - gocritic
    - misspell
    - nilerr
    - noctx
    - prealloc
    - unconvert
    - unparam

  settings:
    errcheck:
      check-type-assertions: true
      exclude-functions:
        - (io.Closer).Close
        - (net/http.Response.Body).Close
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
    misspell:
      locale: US

issues:
  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 5
